name: tilt-extensions
path: .
windows:
  - name: code
    panes:
      - flex: 1
        commands:
          - command: $EDITOR
  - name: misc
    panes:
      - flex: 1
      - flex: 1
  - name: k9s
    panes:
      - commands:
          - command: k9s
